name: first_flutter_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # SQLite (mobile/desktop)
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0

  # ✅ SQLite on Web (WASM + SharedWorker)
  sqflite_common_ffi_web: ^1.0.1+1

  # Paths (ok to keep if you use on mobile/desktop)
  path_provider: ^2.1.1
  path: ^1.8.3

  # Session storage
  shared_preferences: ^2.2.2

  # Password hashing
  crypto: ^3.0.3

  cupertino_icons: ^1.0.8

  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
