server.port=8081
app.cors.allowed-origin=http://localhost:9101

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=anweryahyaoui379@gmail.com
spring.mail.password=lejrmlevijonejwl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Optional, helps with some environments:
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

app.mail.from=travel <anweryahyaoui379@gmail.com>

# Useful while debugging
logging.level.org.springframework.mail=DEBUG
