// lib/models/user.dart
// User model for SQLite database

/**
 * User Model - Represents a user in the app
 * 
 * Fields:
 * - id: Unique identifier (auto-generated by SQLite)
 * - name: User's full name
 * - email: User's email (unique)
 * - password: User's password (hashed in database)
 * 
 * This model:
 * 1. Stores user data
 * 2. Converts from/to Map for SQLite operations
 * 3. Provides JSON methods for future API integration
 */
class User {
  final int? id;         // Nullable because id is auto-generated
  final String name;
  final String email;
  final String password; // Empty string when reading from database (for security)

  User({
    this.id,
    required this.name,
    required this.email,
    required this.password,
  });

  /**
   * Convert User object TO Map
   * Used when: Inserting/Updating user in SQLite
   * 
   * Example:
   * User user = User(name: "Ahmed", email: "ahmed@mail.com", password: "1234");
   * Map<String, dynamic> map = user.toMap();
   * // Result: {"name": "Ahmed", "email": "ahmed@mail.com", "password": "1234"}
   * 
   * Note: id is not included because it's auto-generated by database
   */
  Map<String, dynamic> toMap() {
    return {
      if (id != null) 'id': id,
      'name': name,
      'email': email,
      'password': password,
    };
  }

  /**
   * Create User object FROM Map
   * Used when: Reading user from SQLite database
   * 
   * Example:
   * Map from database: {"id": 1, "name": "Ahmed", "email": "ahmed@mail.com", "password": "hashed"}
   * User user = User.fromMap(map);
   * // Now you can use: user.id, user.name, user.email
   */
  factory User.fromMap(Map<String, dynamic> map) {
    return User(
      id: map['id'] as int?,
      name: map['name'] as String,
      email: map['email'] as String,
      password: '', // Don't expose password for security
    );
  }

  /**
   * Convert User object TO JSON
   * Used for: Future API integration or shared preferences
   */
  Map<String, dynamic> toJson() {
    return {
      if (id != null) 'id': id,
      'name': name,
      'email': email,
      // Don't include password in JSON
    };
  }

  /**
   * Create User object FROM JSON
   * Used for: Reading from shared preferences or API
   */
  factory User.fromJson(Map<String, dynamic> json) {
    return User(
      id: json['id'] as int?,
      name: json['name'] as String? ?? '',
      email: json['email'] as String? ?? '',
      password: '', // Never store password in JSON
    );
  }

  /**
   * Copy user with some fields changed
   * Useful for updating user data
   * 
   * Example:
   * User oldUser = User(id: 1, name: "Ahmed", email: "ahmed@mail.com", password: "");
   * User newUser = oldUser.copyWith(name: "Ahmed Mohamed");
   * // newUser has same id and email, but different name
   */
  User copyWith({
    int? id,
    String? name,
    String? email,
    String? password,
  }) {
    return User(
      id: id ?? this.id,
      name: name ?? this.name,
      email: email ?? this.email,
      password: password ?? this.password,
    );
  }

  @override
  String toString() {
    return 'User(id: $id, name: $name, email: $email)';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is User &&
        other.id == id &&
        other.name == name &&
        other.email == email;
  }

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ email.hashCode;
}